import time
import serial
import binascii
import urllib.request
import os
from function import *

parametry = {
    "0224" : "Procento otevření ventilu",
    "0226" : "RÁM: začátek",
    "1610" : "Pohotovostní",
    "16F9" : "Parametr pro předchozí hodnotu",
    "16EF" : "Číslo datové sady pro ventil (z regulátoru?)",
    "16C2" : "Adresa ventilu",
    "167F" : "Nastavení ventilu provedeno",
    "16C3" : "ventil minMax",
    "1614" : "Teplota ventilu",
    "1624" : "Typ ventilu",
    "15AC" : "% vestavěného otevření ventilu",
    "02F7" : "Nastavení zadané ventilem (z regulátoru)",
    "169E" : "minMax TV",
    "169F" : "minMax TUV",
    "157D" : "Naměřená teplota TV",
    "15A7" : "Typ ovladace",
    "157E" : "Nastavená teplota TV",
    "166E" : "Naměřená teplota TUV",
    "1616" : "Nastavte teplotu TUV",
    "1681" : "Naměřená venkovní teplota",
    "157C" : "Stav jednotky",
    "15CD" : "provozni rezim cerpadla",
    "1620" : "nastaven cas ovladace:",
    "1621" : "nasatveny den ovladace",
    "01F6" : "nastavit teploti TV (od regulatora)",
    "01F9" : "Stav Ovladace",
    "15A7" : "Typ ovladace",
    "16FF" : "Typ ovladace",
    "0365" : "?",
    "0363" : "?",
    "0218" : "RAM: konec [CRC]",
    "01F4" : "Stav ovladace",
    "01F5" : "namerena teplota TV",
    "01F7" : "?",
    "01FD" : "Verze",
    "01FE" : "rucni provoz",
    "01FF" : "Provoz podavace",
    "0200" : "Provoz ventilatoru",
    "0201" : "Provoz cerpadla TV",
    "0203" : "Provoz cerpadla TUV",
    "0209" : "Roztopeni",
    "020A" : "Dohořely",
    "0213" : "rychlost ventilatoru [%]",
    "021F" : "Typ Ovladace",
    "0222" : "Provoz obehoveho cerpadla",
    "0223" : "Provoz podlahoveho cerpadla",
    "0225" : "zrusit Alarm",
    "022F" : "teplota spalin",
    "0245" : "rezim cerpadla",
    "0288" : "Pohotovstni rezim",
    "028C" : "Teplota ventilu",
    "028E" : "Nastavena taplota TUV (z ovladace)",
    "0298" : "Hodina ovladace",
    "0299" : "Den v tydnu ovladace",
    "029C" : "Typ ventilu",
    "02E6" : "Teplota TUV",
    "02F8" : "Funkce ventilu",
    "02F9" : "Venkovni teplota",
    "02FC" : "Zmena nastavene teploty TUV",
    "0301" : "RC",
    "0311" : "Pokojova teplota",
    "0312" : "Nastavena pokojova teplota",
    "0316" : "minMax TV",
    "0317" : "minMax TUV",
    "0322" : "Máme Palivo?",
    "0326" : "provoz pridavneho čerpadla",
    "0328" : "Typ pridavneho cerpadla",
    "0331" : "Cerpadlo ventilu",
    "033A" : "Adresa ventilu",
    "033B" : "minMax ventilu",
    "0343" : "typ letniho rezimu",
    "0367" : "?",
    "0369" : "Hladina paliva",
    "873a" : "Hladina paliva [%]",
    "036A" : "Hodiny paliva",
    "0370" : "Teplota podavace",
    "0377" : "?",
    "0382" : "Zmenit nastaveni vetilu",
    "0383" : "Stav internetoveho modulu",
    "0387" : "Stav hlavniho ovladace",
    "0404" : "nastavit min/max pokojove teploty",
    "0405" : "nastavena pokojova teplota uživatelem",
    "0406" : "nastavit korekci pokojove teploty",
    "1589" : "Cerpadlo TV",
    "158B" : "Cerpadlo TUV",
    "16AE" : "Pridavne čerpadlo",
    "15AB" : "Podlahove cerpadlo",
    "1587" : "Podavac",
    "1588" : "Ventilator",
    "159B" : "Rychlost ventilatoru",
    "16F8" : "Teplota podavace",
    "15B7" : "Teplota spalin",
    "16B6" : "Obehove cerpadlo",
    "16B0" : "pridavne cerpadlo",
    "157F" : "pokojovy Regulator TECH?",
    "1680" : "Stav ventilu",
    "1B66" : "Nastavení maximální pracovní teploty kolektorů",
    "16F1" : "procento paliva v nádrži",
    "16F2" : "přibližná doba dodávky paliva v hodinách (aktualizováno každých 5 minut)",
    "160F" : "maximalni teplota podalhy",
    "15F7" : "Teplota aktivace podlahoveho cerpadla",
    "1771" : "Vyrovnávací čerpadlo (hodnoty 0 a 1, kde 1 je práce)",
    "15AA" : "cirkulační čerpadlo TUV",
    "15A9" : "Tepl. podlahové vytápění (z podlahového čidla)",
    "0988" : "?",
    "09EC" : "?",
    "1699" : "?",
    "16C1" : "Vratná teplota TUV:",
    "16EC" : "?",
}
regval = {
    "0000": "Žádné",
    "0001": "Test",
    "0002": "Práce",
    "0003": "Přestávka",
    "0004": "Podržet operaci",
    "0005": "Podržet pauzu",
    "0006": "Ruční práce",
    "0007": "Zpoždění podavače",
    "0008": "Zpoždění foukání",
    "0009": "Teplota nestoupá",
    "000A": "Poškozený snímač CO",
    "000B": "Teplota CO je příliš vysoká",
    "000C": "Příliš vysoká teplota TUV",
    "000D": "Vadné čidlo TUV",
    "000E": "Vadný snímač podavače",
    "000F": "Teplota podavače je příliš vysoká",
    "0010": "Nastrouhat",
    "0011": "Neúspěšné zapálení",
    "0012": "Vadný snímač výfukových plynů",
    "0013": "Vadné čidlo zpátečky",
    "0014": "Tepelný motor",
    "0015": "Žádná komunikace",
    "0016": "Došlo palivo",
    "0017": "Jazýčkový spínač",
    "0018": "Tepelná ochrana",
    "0019": "Neúspěšná přechodová fáze",
    "001A": "Vypnuto",
    "001B": "Poškozený podlahový senzor",
    "001C": "Zkrat ventilátoru",
    "001D": "Vadné čidlo ventilu",
    "001E": "Ruční práce",
    "001F": "Zapalování",
    "0020": "Násypka",
    "0021": "Zakázáno",
    "0022": "Vyhazování",
    "0023": "Spalování",
    "0024": "Spalování",
    "0025": "Vyčistěte rošt",
    "0026": "Zakázat klepání",
    "0027": "Předem vypněte rošt",
    "0028": "Druhá fáze vypnutí",
    "0029": "Čekání na deaktivaci kropení",
    "002A": "Pohotovostní režim",
    "002B": "Přechodná fáze",
    "002C": "Přechodná fáze",
    "002D": "Zpoždění zapálení",
    "002E": "Modulační práce",
    "002F": "Přerušení modulace",
    "0030": "Test podavače - čekání",
    "0031": "Test podavače",
    "0032": "Foukací test",
    "0033": "Test čerpadla ÚT",
    "0034": "Test čerpadla TUV",
    "0035": "Zápis testu - čekání",
    "0036": "Testovací záznam",
    "0037": "Nastavení servisního kódu",
    "0038": "Přidávání - čekání",
    "0039": "Vypněte přidávání",
    "003A": "Vyhazování",
    "003B": "Vyfouknout",
    "003C": "Vyfouknout",
    "003D": "Požární test",
    "003E": "62",
    "003F": "Měkký start",
    "0040": "Měkký start",
    "0041": "Práce - čekání",
    "0042": "Kalibrace ventilátoru",
    "0043": "Test senzoru spalin",
    "0044" : "68",
    "0045": "Podržet pauzu T2",
    "0046": "operace přidržení T2",
    "0047": "Zpoždění podavače",
    "0048": "Zpoždění foukání",
    "0049": "Práce bez PID",
    "004A": "Podržet pauzu bez PID",
    "004B": "Podržet provoz bez PID",
    "004C": "Předpoplach šneka",
    "004D": "Špatný výběr ventilátoru",
    "004E": "Zapalování",
    "004F": "Zapalování",
    "0050": "Udržovat",
    "0051": "Zpráva",
    "0052": "Dohled",
    "0053": "Pálení rukou",
    "0054": "Pálení rukou",
    "0055": "Pálení rukou",
    "0056": "Požární test",
    "0057": "Požární test",
    "0058": "Požární test",
    "0059": "Posuňte podavač dopředu",
    "005A": "Návrat podavače",
    "005B": "Provoz proudění vzduchu pod dohledem",
    "005C": "Přerušení proudění vzduchu pro dohled",
    "005D": "Měkký start",
    "005E": "Přechodná fáze",
    "005F": "Blokování zakázáno",
    "0060": "Podržet",
    "0061": "Měření spotřeby paliva",
    "00C8": "Senzor ovládání ventilátoru je vadný",
    "00C9": "Rošt s Hallovým efektem",
    "00CA": "Vadný snímač pomocného čerpadla",
    "00CB": "Příliš vysoká teplota ovládání ventilátoru",
    "00CC": "204",
    "00CD": "Žádná komunikace s ventilem",
    "00CE": "Vadný senzor počasí",
    "00CF": "Příliš vysoká teplota podlahy",
    "00D0": "Druhý snímač vyrovnávací paměti je vadný",
    "00D1": "Poškozený senzor pokojské",
    "00D2": "Poškozený snímač vyrovnávací paměti",
    "00D3": "Hallův senzor podavače",
    "00D4": "Solární senzor 1 vadný",
    "00D5": "Snímač Solar 2 je vadný",
    "00D6": "Snímač Solar 3 je vadný",
    "00D7": "Snímač Solar 4 je vadný",
}
kamval = {
    "0000" : "na-> všechna zařízení",
    "FFF4" : "do-> ethernetový modul",
    "FFFA" : "do-> pokojový regulátor Tech",
    "FFF8" : "do-> GSM modulu",
}

print ("RS reading started...")

seru = serial.Serial('/dev/ttyS0', baudrate=9600,
                    parity=serial.PARITY_NONE,
                    stopbits=serial.STOPBITS_ONE,
                    bytesize=serial.EIGHTBITS, timeout = 1)

while True:
        i = seru.readline()
        a = i.hex()
        a = a.upper()
        a.strip()
        #print(a)
        #print (len(a))
        crc_cajk = porovnej_crc(a)
        if ( crc_cajk != True ):
             #print ("spatne crc")
             continue

        y = 0
        for x in range(len(a)):
            if a[y:y+4] in parametry:
               parametr = a[y:y+4]
               data = a[y+4:y+8]
               dataDec = int(a[y+4:y+8],16)
               popis = parametry[a[y:y+4]]
               if (parametr == "16F8" or parametr == "15B7" or parametr == "157D" or parametr == "166E") :
                  dataDec = dataDec/10
               dataStr = str(dataDec)
               minus = (6 - int(len(dataStr)))
               dataLen = len(dataStr)
               dataStr = dataStr.ljust(minus)
               #dataStr = dataStr.left(5 - len(dataStr))
               print (parametr, data, dataStr,"--", popis,)
               #print (a[y:y+4],"--",parametry[a[y:y+4]],"--",a[y+4:y+8])
	       #print (parametry[a[y:y+4]])
            #else:
               #print(a[y:y+4], "-- nebyl nalezen")
            y = y + 8
            if (y >= len(a)):
                break
