parametry = {
    "0224" : "Procento otevreni ventilu,proc,,False",
    "0226" : "RaM: zacatek,,,False",
    "1610" : "Pohotovostni,,,False",
    "16F9" : "Parametr pro predchozi hodnotu,,,False",
    "16EF" : "cislo datove sady pro ventil (z regulatoru?),,,False",
    "16C2" : "Adresa ventilu,,,False",
    "167F" : "Nastaveni ventilu provedeno,,,False",
    "16C3" : "ventil minMax,temp,,False",
    "1614" : "Teplota ventilu,temp,,False",
    "1624" : "Typ ventilu,,,False",
    "15AC" : "% vestaveneho otevreni ventilu,temp,,False",
    "02F7" : "Nastaveni zadane ventilem (z regulatoru),,,False",
    "169E" : "minMax TV,temp,,False",
    "169F" : "minMax TUV,temp,,False",
    "157D" : "Namerena teplota TV,temp,,True",
    "15A7" : "Typ ovladace,,,False",
    "157E" : "Nastavena teplota TV,settemp,,True",
    "166E" : "Namerena teplota TUV,temp,,True",
    "1616" : "Nastavte teplotu TUV,settemp,,True",
    "1681" : "Namerena venkovni teplota,temp,,False",
    "157C" : "Stav jednotky,stav,,True",
    "15CD" : "provozni rezim cerpadla,selswitch,,True",
    "1620" : "nastaven cas ovladace:,,,False",
    "1621" : "nasatveny den ovladace,stav,,False",
    "01F6" : "nastavit teplotu TV (od regulatora),,,False",
    "01F9" : "Stav Ovladace,,,False",
    "15A7" : "Typ ovladace,stav,,False",
    "16FF" : "Typ ovladace,stav,,False",
    "0365" : "?,,,False",
    "0363" : "?,,,False",
    "0218" : "RAM: konec [CRC],,,False",
    "01F4" : "Stav ovladace,stav,,False",
    "01F5" : "namerena teplota TV,temp,,False",
    "01F7" : "?,,,False",
    "01FD" : "Verze,,,False",
    "01FE" : "rucni provoz,switch,,False",
    "01FF" : "Provoz podavace,switch,,False",
    "0200" : "Provoz ventilatoru,switch,,False",
    "0201" : "Provoz cerpadla TV,switch,,False",
    "0203" : "Provoz cerpadla TUV,switch,,False",
    "0209" : "Roztopeni,switch,,False",
    "020A" : "Dohorely,switch,,False",
    "0213" : "rychlost ventilatoru [%],proc,,False",
    "021F" : "Typ Ovladace,,,False",
    "0222" : "Provoz obehoveho cerpadla,switch,,False",
    "0223" : "Provoz podlahoveho cerpadla,switch,,False",
    "0225" : "zrusit Alarm,switch,,False",
    "022F" : "teplota spalin,temp,,False",
    "0245" : "rezim cerpadla,stav,,False",
    "0288" : "Pohotovstni rezim,switch,,False",
    "028C" : "Teplota ventilu,temp,,False",
    "028E" : "Nastavena taplota TUV (z ovladace),temp,,False",
    "0298" : "Hodina ovladace,,,False",
    "0299" : "Den v tydnu ovladace,stav,,False",
    "029C" : "Typ ventilu,,,False",
    "02E6" : "Teplota TUV,temp,,False",
    "02F8" : "Funkce ventilu,temp,,False",
    "02F9" : "Venkovni teplota,temp,,False",
    "02FC" : "Zmena nastavene teploty TUV,temp,,False",
    "0301" : "RC,,,False",
    "0311" : "Pokojova teplota,temp,,False",
    "0312" : "Nastavena pokojova teplota,term,,False",
    "0316" : "minMax TV,temp,,False",
    "0317" : "minMax TUV,temp,,False",
    "0322" : "Mame Palivo?,,,False",
    "0326" : "provoz pridavneho cerpadla,switch,,False",
    "0328" : "Typ pridavneho cerpadla,,,False",
    "0331" : "Cerpadlo ventilu,,,False",
    "033A" : "Adresa ventilu,,,False",
    "033B" : "minMax ventilu,,,False",
    "0343" : "typ letniho rezimu,,,False",
    "0367" : "?,,,False",
    "0369" : "Hladina paliva,text,,False",
    "873a" : "Hladina paliva [%],proc,,False",
    "036A" : "Hodiny paliva,text,,False",
    "0370" : "Teplota podavace,temp,,True",
    "0377" : "?,,,False",
    "0382" : "Zmenit nastaveni vetilu,switch,,False",
    "0383" : "Stav internetoveho modulu,switch,,False",
    "0387" : "Stav hlavniho ovladace,,,False",
    "0404" : "nastavit min/max pokojove teploty,temp,,False",
    "0405" : "nastavena pokojova teplota uzivatelem,temp,,False",
    "0406" : "nastavit korekci pokojove teploty,temp,,False",
    "1589" : "Cerpadlo TV,switch,,True",
    "158B" : "Cerpadlo TUV,switch,,True",
    "16AE" : "Pridavne cerpadlo,switch,,False",
    "15AB" : "Podlahove cerpadlo,switch,,False",
    "1587" : "Podavac,switch,,True",
    "1588" : "Ventilator On/Off,switch,,True",
    "159B" : "Rychlost ventilatoru,proc,,True",
    "16F8" : "Teplota podavace,temp,,True",
    "15B7" : "Teplota spalin,temp,,True",
    "16B6" : "Obehove cerpadlo,switch,,False",
    "16B0" : "pridavne cerpadlo,switch,,False",
    "157F" : "pokojovy Regulator TECH?,switch,,False",
    "1680" : "Stav ventilu,,,False",
    "1B66" : "Nastaveni maximalni pracovni teploty kolektorů,temp,,False",
    "16F1" : "procento paliva v nadrzi,proc,,True",
    "16F2" : "priblizna doba dodavky paliva v hodinach (aktualizovano kazdych 5 minut),text,,True",
    "160F" : "maximalni teplota podalhy,temp,,False",
    "15F7" : "Teplota aktivace podlahoveho cerpadla,temp,,False",
    "1771" : "Vyrovnavaci cerpadlo,switch,,False",
    "15AA" : "cirkulacni cerpadlo TUV,switch,,False",
    "15A9" : "Tepl. podlahove vytapeni (z podlahoveho cidla),temp,,False",
    "0988" : "?,,,False",
    "09EC" : "?,,,False",
    "1699" : "?,,,False",
    "16C1" : "Vratna teplota TUV:,temp,,False",
    "16EC" : "?,,,False",
}
regval = {
    "0000": "zadne",
    "0001": "Test",
    "0002": "Prace",
    "0003": "Prestavka",
    "0004": "Podrzet operaci",
    "0005": "Podrzet pauzu",
    "0006": "Rucni prace",
    "0007": "Zpozdeni podavace",
    "0008": "Zpozdeni foukani",
    "0009": "Teplota nestoupa",
    "000A": "Poskozeny snimac CO",
    "000B": "Teplota CO je prilis vysoka",
    "000C": "Prilis vysoka teplota TUV",
    "000D": "Vadne cidlo TUV",
    "000E": "Vadny snimac podavace",
    "000F": "Teplota podavace je prilis vysoka",
    "0010": "Nastrouhat",
    "0011": "Neúspesne zapaleni",
    "0012": "Vadny snimac vyfukovych plynů",
    "0013": "Vadne cidlo zpatecky",
    "0014": "Tepelny motor",
    "0015": "zadna komunikace",
    "0016": "Doslo palivo",
    "0017": "Jazyckovy spinac",
    "0018": "Tepelna ochrana",
    "0019": "Neúspesna prechodova faze",
    "001A": "Vypnuto",
    "001B": "Poskozeny podlahovy senzor",
    "001C": "Zkrat ventilatoru",
    "001D": "Vadne cidlo ventilu",
    "001E": "Rucni prace",
    "001F": "Zapalovani",
    "0020": "Nasypka",
    "0021": "Zakazano",
    "0022": "Vyhazovani",
    "0023": "Spalovani",
    "0024": "Spalovani",
    "0025": "Vycistete rost",
    "0026": "Zakazat klepani",
    "0027": "Predem vypnete rost",
    "0028": "Druha faze vypnuti",
    "0029": "cekani na deaktivaci kropeni",
    "002A": "Pohotovostni rezim",
    "002B": "Prechodna faze",
    "002C": "Prechodna faze",
    "002D": "Zpozdeni zapaleni",
    "002E": "Modulacni prace",
    "002F": "Preruseni modulace",
    "0030": "Test podavace - cekani",
    "0031": "Test podavace",
    "0032": "Foukaci test",
    "0033": "Test cerpadla ÚT",
    "0034": "Test cerpadla TUV",
    "0035": "Zapis testu - cekani",
    "0036": "Testovaci zaznam",
    "0037": "Nastaveni servisniho kódu",
    "0038": "Pridavani - cekani",
    "0039": "Vypnete pridavani",
    "003A": "Vyhazovani",
    "003B": "Vyfouknout",
    "003C": "Vyfouknout",
    "003D": "Pozarni test",
    "003E": "62",
    "003F": "Mekky start",
    "0040": "Mekky start",
    "0041": "Prace - cekani",
    "0042": "Kalibrace ventilatoru",
    "0043": "Test senzoru spalin",
    "0044" : "68",
    "0045": "Podrzet pauzu T2",
    "0046": "operace pridrzeni T2",
    "0047": "Zpozdeni podavace",
    "0048": "Zpozdeni foukani",
    "0049": "Prace bez PID",
    "004A": "Podrzet pauzu bez PID",
    "004B": "Podrzet provoz bez PID",
    "004C": "Predpoplach sneka",
    "004D": "spatny vyber ventilatoru",
    "004E": "Zapalovani",
    "004F": "Zapalovani",
    "0050": "Udrzovat",
    "0051": "Zprava",
    "0052": "Dohled",
    "0053": "Paleni rukou",
    "0054": "Paleni rukou",
    "0055": "Paleni rukou",
    "0056": "Pozarni test",
    "0057": "Pozarni test",
    "0058": "Pozarni test",
    "0059": "Posuňte podavac dopredu",
    "005A": "Navrat podavace",
    "005B": "Provoz proudeni vzduchu pod dohledem",
    "005C": "Preruseni proudeni vzduchu pro dohled",
    "005D": "Mekky start",
    "005E": "Prechodna faze",
    "005F": "Blokovani zakazano",
    "0060": "Podrzet",
    "0061": "Mereni spotreby paliva",
    "00C8": "Senzor ovladani ventilatoru je vadny",
    "00C9": "Rost s Hallovym efektem",
    "00CA": "Vadny snimac pomocneho cerpadla",
    "00CB": "Prilis vysoka teplota ovladani ventilatoru",
    "00CC": "204",
    "00CD": "zadna komunikace s ventilem",
    "00CE": "Vadny senzor pocasi",
    "00CF": "Prilis vysoka teplota podlahy",
    "00D0": "Druhy snimac vyrovnavaci pameti je vadny",
    "00D1": "Poskozeny senzor pokojske",
    "00D2": "Poskozeny snimac vyrovnavaci pameti",
    "00D3": "Hallův senzor podavace",
    "00D4": "Solarni senzor 1 vadny",
    "00D5": "Snimac Solar 2 je vadny",
    "00D6": "Snimac Solar 3 je vadny",
    "00D7": "Snimac Solar 4 je vadny",
}
kamval = {
    "0000" : "na-> vsechna zarizeni",
    "FFF4" : "do-> ethernetovy modul",
    "FFFA" : "do-> pokojovy regulator Tech",
    "FFF8" : "do-> GSM modulu",
}
